Repository dnd-side-project/dnd-5th-6-repo, pull requests merged in 2021-07, with the labels that each got.

#3 [feat] BE Skeleton Code
  .gitignore
  DnD-5th-6-Project.iml
  Server/apollo-instance.js
  Server/index.js
  Server/lib/resolver/users.js
  Server/lib/schema/_schema.js
  Server/lib/typeDefs/Mutation.js
  Server/lib/typeDefs/Query.js
  Server/package-lock.json
  Server/package.json
  package-lock.json
  package.json
Labels: Back-End

#4 Prisma Setting, Add Create, Read Example(PR #4)
  Server/apollo-instance.js
  Server/lib/model/.env
  Server/lib/model/schema.prisma
  Server/lib/resolver/users.js
  Server/lib/typeDefs/Mutation.js
  Server/lib/typeDefs/Query.js
  Server/package-lock.json
  Server/package.json
Labels: Back-End

#5 [feat] Prisma Update, Delete API Example
  Server/lib/resolver/users.js
  Server/lib/typeDefs/Mutation.js
  Server/package-lock.json
  Server/package.json
Labels: Back-End

#6 [docs] Add Test (PR #5)
  .DS_Store
  Client/index.html
  Server/.DS_Store
  Server/prisma/schema.prisma
Labels: Front-End

#7 [feat] Add Skeleton Code
  Client/buddy/.gitignore
  Client/buddy/package.json
  Client/buddy/public/favicon.ico
  Client/buddy/public/index.html
  Client/buddy/src/app.jsx
  Client/buddy/src/app.module.css
  Client/buddy/src/index.js
  Client/buddy/src/index.module.css
  Client/buddy/yarn.lock
  Client/index.html
  Client/package.json
Labels: Front-End

#8 [feat] naver login API test
  Server/lib/resolver-utils/validation.js
  Server/lib/resolver/users.js
  Server/package-lock.json
  Server/package.json
Labels: Back-End

#9 [feat] naver 사용자 조회 API
  Server/lib/resolver-utils/NaverUserInfo.js
  Server/lib/resolver-utils/validation.js
  Server/lib/resolver/users.js
  Server/lib/typeDefs/Query.js
Labels: Back-End

#10 [feat] naver user duplicate 여부 조회 logic
  Server/lib/resolver-utils/NaverUserInfo.js
  Server/lib/resolver/users.js
Labels: Back-End

#11 [feat] naver login token 가져오기
  Client/buddy/.gitignore
  Client/buddy/package.json
  Client/buddy/public/index.html
  Client/buddy/src/app.jsx
  Client/buddy/src/components/naverLogin.jsx
  Client/buddy/yarn.lock
Labels: Front-End

#12 Feature/db insert userinfo
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  Server/lib/resolver-utils/NaverUserInfo.js
  Server/lib/resolver-utils/UserAuth.js
  Server/lib/resolver/users.js
  Server/package-lock.json
  Server/package.json
Labels: Back-End

#13 Merge for integration
  .DS_Store
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  Client/buddy/.gitignore
  Client/buddy/package.json
  Client/buddy/public/favicon.ico
  Client/buddy/public/index.html
  Client/buddy/src/app.jsx
  Client/buddy/src/app.module.css
  Client/buddy/src/components/naverLogin.jsx
  Client/buddy/src/index.js
  Client/buddy/src/index.module.css
  Client/buddy/yarn.lock
  Client/index.html
  Client/package.json
  Server/.DS_Store
  Server/apollo-instance.js
  Server/lib/model/.env
  Server/lib/model/schema.prisma
  Server/lib/resolver-utils/NaverUserInfo.js
  Server/lib/resolver-utils/UserAuth.js
  Server/lib/resolver/users.js
  Server/lib/typeDefs/Mutation.js
  Server/lib/typeDefs/Query.js
  Server/package-lock.json
  Server/package.json
  Server/prisma/schema.prisma
Labels: Back-End, Front-End

#14 [feat] Jest Package 추가(Root) 및 세팅
  Server/.env
  Server/__test__/test.js
  Server/apollo-instance.js
  Server/package.json
  package-lock.json
  package.json
Labels: Back-End, Front-End

#16 [refector] Return 값 변경, 네이버 로그인시 Nickname 생성
  Server/lib/resolver-utils/NaverUserInfo.js
  Server/lib/resolver/users.js
Labels: Back-End

#17 [refactor] naver login 성공 시 return 값 변경
  Server/lib/resolver-utils/NaverUserInfo.js
  Server/lib/resolver/users.js
Labels: Back-End

#19 [feat] kakao login API
  Server/lib/model/schema.prisma
  Server/lib/resolver-utils/SocialLogin.js
  Server/lib/resolver/users.js
  Server/lib/typeDefs/Query.js
Labels: Back-End

#20 [refactor] prisma 스키마 변경 및 리팩토링
  Server/lib/model/schema.prisma
  Server/lib/resolver-utils/SocialLogin.js
  Server/lib/resolver/users.js
Labels: Back-End

#18 [feat] ApolloClient setting
  Client/buddy/package.json
  Client/buddy/src/apollo.js
  Client/buddy/src/components/naverLogin.jsx
  Client/buddy/src/index.js
  Client/buddy/yarn.lock
Labels: Front-End

#22 [feat] Add API: getAllLatestPost
  Server/index.js
  Server/lib/model/schema.prisma
  Server/lib/resolver-utils/UserAuth.js
  Server/lib/resolver-utils/getFeeds.js
  Server/lib/resolver/feeds.js
  Server/lib/typeDefs/Query.js
  Server/package-lock.json
  Server/package.json
  package-lock.json
  package.json
Labels: Back-End

#23 [feat] 메인페이지 UI 세팅
  Client/buddy/src/app.jsx
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardItem/cardItem.module.css
  Client/buddy/src/components/cardList/cardList.jsx
  Client/buddy/src/components/cardList/cardList.module.css
  Client/buddy/src/components/login/naverLogin.jsx
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/components/selectOption/selectOption.jsx
  Client/buddy/src/components/selectOption/selectOption.module.css
  Client/buddy/src/routes/main.jsx
  Client/buddy/src/routes/record.jsx
  Client/buddy/src/routes/report.jsx
Labels: Front-End

#25 [feat] post 등록 유저 닉네임, 좋아요 수 추출 [fix] 날짜 리턴 형식 수정
  Server/lib/resolver-utils/getFeeds.js
Labels: Back-End

#26 [fix] feedOpen 1인 값만 출력, JWT decode 과정 임시 삭제
  Server/lib/resolver-utils/getFeeds.js
Labels: Back-End

#28 Feature/login
  Client/buddy/public/index.html
  Client/buddy/src/apollo.js
  Client/buddy/src/apollo/apollo.js
  Client/buddy/src/app.jsx
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardItem/cardItem.module.css
  Client/buddy/src/components/cardList/cardList.jsx
  Client/buddy/src/components/cardList/cardList.module.css
  Client/buddy/src/components/login/kakaoLogin.jsx
  Client/buddy/src/components/login/login.module.css
  Client/buddy/src/components/login/naverLogin.jsx
  Client/buddy/src/components/selectOption/selectOption.jsx
  Client/buddy/src/index.js
  Client/buddy/src/routes/main.jsx
Labels: Front-End

#27 Feature/modify schema
  Server/lib/resolver-utils/getFeeds.js
  Server/lib/resolver/feeds.js
  Server/lib/schema/_schema.js
  Server/lib/typeDefs/Query.js
Labels: Back-End, Front-End

#29 Develop -> Master PR
  .gitignore
  Client/buddy/package-lock.json
  Client/buddy/package.json
  Client/buddy/public/index.html
  Client/buddy/src/apollo/apollo.js
  Client/buddy/src/app.jsx
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardItem/cardItem.module.css
  Client/buddy/src/components/cardList/cardList.jsx
  Client/buddy/src/components/cardList/cardList.module.css
  Client/buddy/src/components/login/kakaoLogin.jsx
  Client/buddy/src/components/login/login.module.css
  Client/buddy/src/components/login/naverLogin.jsx
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/components/naverLogin.jsx
  Client/buddy/src/components/selectOption/selectOption.jsx
  Client/buddy/src/components/selectOption/selectOption.module.css
  Client/buddy/src/index.js
  Client/buddy/src/routes/main.jsx
  Client/buddy/src/routes/record.jsx
  Client/buddy/src/routes/report.jsx
  Client/buddy/yarn.lock
  Server/__test__/test.js
  Server/apollo-instance.js
  Server/index.js
  Server/lib/model/schema.prisma
  Server/lib/resolver-utils/NaverUserInfo.js
  Server/lib/resolver-utils/SocialLogin.js
  Server/lib/resolver-utils/UserAuth.js
  Server/lib/resolver-utils/getFeeds.js
  Server/lib/resolver/feeds.js
  Server/lib/resolver/users.js
  Server/lib/schema/_schema.js
  Server/lib/typeDefs/Query.js
  Server/package-lock.json
  Server/package.json
  package-lock.json
  package.json
Labels: Back-End, Front-End

#30 [feat] 카드 좋아요 클릭 여부 확인
  Server/lib/resolver-utils/getFeeds.js
Labels: Back-End

#31 Feature/main UI 1
  Client/buddy/src/apollo/apollo.js
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardItem/cardItem.module.css
  Client/buddy/src/components/cardList/cardList.jsx
  Client/buddy/src/components/cardList/cardList.module.css
  Client/buddy/src/components/login/kakaoLogin.jsx
  Client/buddy/src/components/login/naverLogin.jsx
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/routes/main.jsx
Labels: Front-End

#33 Feature/api feed popular
  Server/.dockerignore
  Server/Dockerfile
  Server/lib/resolver-utils/getFeeds.js
  Server/lib/schema/_schema.js
  Server/lib/typeDefs/Query.js
Labels: Back-End

#34 Develop
  Server/.dockerignore
  Server/Dockerfile
  Server/docker-compose.yml
  Server/lib/resolver-utils/getFeeds.js
  Server/lib/resolver/feeds.js
  Server/lib/resolver/users.js
  Server/lib/schema/_schema.js
  Server/lib/typeDefs/Mutation.js
  Server/lib/typeDefs/Query.js
  Server/package-lock.json
  Server/package.json
  Server/prisma/schema.prisma
Labels: Back-End, Front-End

#35 [feat] 메인 피드 인기순, 종목순
  Server/lib/model/schema.prisma
  Server/lib/resolver-utils/getFeeds.js
  Server/lib/resolver/feeds.js
  Server/lib/typeDefs/Query.js
Labels: Back-End

#36 Feature/main UI 1
  Client/buddy/package.json
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardItem/cardItem.module.css
  Client/buddy/src/components/cardList/cardList.jsx
  Client/buddy/src/components/modal/cardModal.jsx
  Client/buddy/src/components/modal/cardModal.module.css
  Client/buddy/src/index.js
  Client/buddy/yarn.lock
Labels: Front-End

#37 [refactor] 코드 리팩터링
  Server/lib/resolver-utils/getFeeds.js
  Server/lib/resolver/feeds.js
Labels: Back-End

#39 [refactor] apollo 쿼리 파일 추출
  Client/buddy/src/apollo/apollo.js
  Client/buddy/src/apollo/queries/CardItem/getCard.js
  Client/buddy/src/apollo/queries/login/login.js
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardItem/cardItem.module.css
  Client/buddy/src/components/cardList/cardList.jsx
  Client/buddy/src/components/login/kakaoLogin.jsx
  Client/buddy/src/components/login/naverLogin.jsx
Labels: Front-End

#38 [feat] 좋아요 누르기 API
  Server/lib/resolver-utils/UserAuth.js
  Server/lib/resolver-utils/getFeeds.js
  Server/lib/resolver-utils/likePost.js
  Server/lib/resolver/feeds.js
  Server/lib/typeDefs/Mutation.js
Labels: Back-End
