Repository dnd-side-project/dnd-5th-6-repo, pull requests merged in 2021-08, with the labels that each got.

#40 Feature/like modify
  Server/lib/resolver-utils/likePost.js
  Server/lib/typeDefs/Mutation.js
Labels: Back-End

#42 [feat]카드 리스트 정렬 기준 추가
  Client/buddy/src/apollo/apollo.js
  Client/buddy/src/apollo/cache.js
  Client/buddy/src/apollo/localState.js
  Client/buddy/src/apollo/queries/CardItem/getCard.js
  Client/buddy/src/apollo/queries/login/login.js
  Client/buddy/src/apollo/queries/users/users.js
  Client/buddy/src/components/button/button.jsx
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardItem/cardItem.module.css
  Client/buddy/src/components/cardList/cardList.jsx
  Client/buddy/src/components/like/like.jsx
  Client/buddy/src/components/like/like.module.css
  Client/buddy/src/components/login/naverLogin.jsx
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/components/selectOption/selectOption.jsx
  Client/buddy/src/components/selectOption/selectOption.module.css
  Client/buddy/src/data/exercises/exercises.js
  Client/buddy/src/routes/main.jsx
  Client/buddy/src/routes/myPage.jsx
Labels: Front-End

#44 [feat] 기록 등록 API
  Server/lib/resolver-utils/Post.js
  Server/lib/resolver/feeds.js
  Server/lib/typeDefs/Mutation.js
  buildspec.yml
Labels: Back-End

#45 [feat] 정보 제공 추가
  Client/buddy/jsconfig.json
  Client/buddy/src/apollo/queries/CardItem/like.js
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/like/like.jsx
  Client/buddy/src/components/login/naverLogin.jsx
  Client/buddy/src/components/selectOption/selectOption.jsx
Labels: Front-End

#46 [feat] 리포팅 API 추가
  Server/lib/resolver-utils/Post.js
  Server/lib/resolver/feeds.js
  Server/lib/typeDefs/Query.js
Labels: Back-End

#47 [feat]main css 정리 및 달력 기초
  Client/buddy/package.json
  Client/buddy/src/app.jsx
  Client/buddy/src/components/button/button.jsx
  Client/buddy/src/components/calendar/calendar.jsx
  Client/buddy/src/components/calendar/calendar.module.css
  Client/buddy/src/components/cardList/cardList.module.css
  Client/buddy/src/components/navBar/hamburger.svg
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/components/navBar/pacebuddylogo.svg
  Client/buddy/src/components/selectOption/selectOption.jsx
  Client/buddy/src/components/selectOption/selectOption.module.css
  Client/buddy/src/routes/main.jsx
  Client/buddy/src/routes/record.jsx
  Client/buddy/yarn.lock
Labels: Front-End

#48 Develop
  Client/buddy/jsconfig.json
  Client/buddy/package.json
  Client/buddy/src/apollo/apollo.js
  Client/buddy/src/apollo/cache.js
  Client/buddy/src/apollo/localState.js
  Client/buddy/src/apollo/queries/CardItem/getCard.js
  Client/buddy/src/apollo/queries/CardItem/like.js
  Client/buddy/src/apollo/queries/login/login.js
  Client/buddy/src/apollo/queries/users/users.js
  Client/buddy/src/app.jsx
  Client/buddy/src/components/button/button.jsx
  Client/buddy/src/components/calendar/calendar.jsx
  Client/buddy/src/components/calendar/calendar.module.css
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardItem/cardItem.module.css
  Client/buddy/src/components/cardList/cardList.jsx
  Client/buddy/src/components/cardList/cardList.module.css
  Client/buddy/src/components/like/like.jsx
  Client/buddy/src/components/like/like.module.css
  Client/buddy/src/components/login/naverLogin.jsx
  Client/buddy/src/components/navBar/hamburger.svg
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/components/navBar/pacebuddylogo.svg
  Client/buddy/src/components/selectOption/selectOption.jsx
  Client/buddy/src/components/selectOption/selectOption.module.css
  Client/buddy/src/data/exercises/exercises.js
  Client/buddy/src/routes/main.jsx
  Client/buddy/src/routes/myPage.jsx
  Client/buddy/src/routes/record.jsx
  Client/buddy/yarn.lock
  Server/lib/resolver-utils/Post.js
  Server/lib/resolver-utils/getFeeds.js
  Server/lib/resolver-utils/likePost.js
  Server/lib/resolver/feeds.js
  Server/lib/typeDefs/Mutation.js
  Server/lib/typeDefs/Query.js
Labels: Back-End, Front-End

#49 Feature/like
  Client/buddy/src/apollo/queries/CardItem/like.js
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardList/cardList.jsx
  Client/buddy/src/components/like/like.jsx
  Client/buddy/src/components/like/like.module.css
  Client/buddy/src/components/navBar/hamburger.svg
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/navBar/pacebuddylogo.svg
  Client/buddy/src/icons.js
  Client/buddy/src/routes/record.jsx
Labels: Front-End

#50 [refactor] 운동 인덱스 값 수정
  Server/lib/model/schema.prisma
  Server/lib/resolver-utils/Post.js
  Server/lib/resolver-utils/getFeeds.js
  Server/lib/resolver/feeds.js
  Server/lib/schema/_schema.js
  Server/lib/typeDefs/Query.js
Labels: Back-End

#51 [test] 테스트 환경 세팅 및 피드 테스트 추가
  Server/__test__/feed.test.js
  Server/__test__/test_setup.js
  Server/__test__/user.test.js
  Server/apollo-instance.js
  Server/index.js
  Server/package-lock.json
  Server/package.json
Labels: Back-End

#52 [feat]로그인/로그아웃 판별
  Client/buddy/src/apollo/apollo.js
  Client/buddy/src/apollo/localState.js
  Client/buddy/src/apollo/queries/exercises/getExercises.js
  Client/buddy/src/app.jsx
  Client/buddy/src/components/cardItem/Group 31.svg
  Client/buddy/src/components/cardItem/feed_card_weather.svg
  Client/buddy/src/components/cardItem/image.js
  Client/buddy/src/components/cardList/cardList.jsx
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/components/navBar/navbarcontents.jsx
  Client/buddy/src/components/selectOption/selectOption.jsx
  Client/buddy/src/components/selectOption/selectOption.module.css
  Client/buddy/src/icons.js
  Client/buddy/src/routes/navbar.jsx
  Client/buddy/src/routes/record.jsx
Labels: Front-End

#53 Develop -> Master
  Client/buddy/src/apollo/apollo.js
  Client/buddy/src/apollo/localState.js
  Client/buddy/src/apollo/queries/CardItem/like.js
  Client/buddy/src/apollo/queries/exercises/getExercises.js
  Client/buddy/src/app.jsx
  Client/buddy/src/components/cardItem/Group 31.svg
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardItem/feed_card_weather.svg
  Client/buddy/src/components/cardItem/image.js
  Client/buddy/src/components/cardList/cardList.jsx
  Client/buddy/src/components/like/like.jsx
  Client/buddy/src/components/like/like.module.css
  Client/buddy/src/components/navBar/hamburger.svg
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/components/navBar/navbarcontents.jsx
  Client/buddy/src/components/navBar/pacebuddylogo.svg
  Client/buddy/src/components/selectOption/selectOption.jsx
  Client/buddy/src/components/selectOption/selectOption.module.css
  Client/buddy/src/icons.js
  Client/buddy/src/routes/navbar.jsx
  Client/buddy/src/routes/record.jsx
  Server/__test__/feed.test.js
  Server/__test__/test_setup.js
  Server/__test__/user.test.js
  Server/apollo-instance.js
  Server/index.js
  Server/lib/model/schema.prisma
  Server/lib/resolver-utils/Post.js
  Server/lib/resolver-utils/getFeeds.js
  Server/lib/resolver/feeds.js
  Server/lib/schema/_schema.js
  Server/lib/typeDefs/Query.js
  Server/package-lock.json
  Server/package.json
Labels: Front-End, Back-End

#55 [fix] cardImgIndex 컬럼 삭제
  Server/lib/model/schema.prisma
  Server/lib/resolver-utils/Post.js
  Server/lib/schema/_schema.js
Labels: Back-End

#56 [feat] 내 기록 날짜 불러오기 API
  Server/lib/resolver-utils/getFeeds.js
  Server/lib/resolver/feeds.js
  Server/lib/schema/_schema.js
  Server/lib/typeDefs/Query.js
Labels: Back-End

#57 Feature/card list
  Client/buddy/public/images/conditions/condition1.svg
  Client/buddy/public/images/exercises/exercise1.svg
  Client/buddy/src/apollo/queries/CardItem/getCard.js
  Client/buddy/src/apollo/queries/exercises/getExercises.js
  Client/buddy/src/app.jsx
  Client/buddy/src/components/button/button.jsx
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardItem/cardItem.module.css
  Client/buddy/src/components/cardList/cardList.jsx
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/recordPost/recordPost.jsx
  Client/buddy/src/components/recordPost/recordPost.module.css
  Client/buddy/src/components/selectOption/selectOption.jsx
  Client/buddy/src/components/toggle/toggle.jsx
  Client/buddy/src/data/exercises/exercises.js
  Client/buddy/src/icons.js
  Client/buddy/src/routes/Post.jsx
  Client/buddy/src/routes/main.jsx
  Client/buddy/src/routes/record.jsx
  Client/buddy/src/services/card_list.js
  Client/buddy/src/services/card_post.js
  Client/buddy/src/weathers.js
  package.json
  yarn.lock
Labels: Front-End

#58 [feat]기록 empty 화면
  Client/buddy/src/apollo/queries/CardItem/addCard.js
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/recordBar/recordBar.jsx
  Client/buddy/src/components/recordBar/recordBar.module.css
  Client/buddy/src/components/selectOption/selectOption.jsx
  Client/buddy/src/icons.js
  Client/buddy/src/routes/record.jsx
Labels: Front-End

#60 [feat]카드 일러스트 추가
  Client/buddy/package.json
  Client/buddy/public/images/conditions/condition1.svg
  Client/buddy/public/images/conditions/condition2.svg
  Client/buddy/public/images/conditions/condition3.svg
  Client/buddy/public/images/conditions/condition4.svg
  Client/buddy/public/images/conditions/condition5.svg
  Client/buddy/public/images/exercises/exercise1.svg
  Client/buddy/public/images/exercises/exercise10.svg
  Client/buddy/public/images/exercises/exercise11.svg
  Client/buddy/public/images/exercises/exercise2.svg
  Client/buddy/public/images/exercises/exercise3.svg
  Client/buddy/public/images/exercises/exercise4.svg
  Client/buddy/public/images/exercises/exercise6.svg
  Client/buddy/public/images/exercises/exercise7.svg
  Client/buddy/public/images/exercises/exercise8.svg
  Client/buddy/public/images/exercises/exercise9.svg
  Client/buddy/src/components/cardItem/Group 31.svg
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardItem/cardItem.module.css
  Client/buddy/src/components/cardItem/feed_card_weather.svg
  Client/buddy/src/components/cardItem/image.js
  Client/buddy/src/components/recordBar/recordBar.module.css
  Client/buddy/src/components/recordPost/recordPost.module.css
  Client/buddy/yarn.lock
Labels: Front-End

#61 [fix] getMyPost API 리턴 데이터 수정
  Server/lib/resolver-utils/getFeeds.js
Labels: Back-End

#62 [feat]내 기록 보기
  Client/buddy/public/index.html
  Client/buddy/src/apollo/queries/CardItem/getCard.js
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardItem/cardItem.module.css
  Client/buddy/src/components/cardList/cardList.module.css
  Client/buddy/src/components/modal/cardModal.module.css
  Client/buddy/src/components/recordBar/recordBar.module.css
  Client/buddy/src/components/recordPost/recordPost.jsx
  Client/buddy/src/components/recordPost/recordPost.module.css
  Client/buddy/src/components/selectOption/selectOption.module.css
  Client/buddy/src/icons.js
  Client/buddy/src/routes/main.jsx
  Client/buddy/src/routes/record.jsx
Labels: Front-End

#64 [feat]로그인에 따른 기록 화면 분기
  Client/buddy/src/apollo/queries/CardItem/getCard.js
  Client/buddy/src/app.jsx
  Client/buddy/src/app.module.css
  Client/buddy/src/components/login/naverLogin.jsx
  Client/buddy/src/components/modal/twoButtonModal.jsx
  Client/buddy/src/components/modal/twoButtonModal.module.css
  Client/buddy/src/components/recordBar/recordBar.jsx
  Client/buddy/src/components/recordFeed/recordFeed.jsx
  Client/buddy/src/components/recordFeed/recordFeed.module.css
  Client/buddy/src/icons.js
  Client/buddy/src/routes/login.jsx
  Client/buddy/src/routes/record.jsx
Labels: Front-End

#65 [style] 날짜 리턴 형식 변경
  Server/lib/resolver-utils/getFeeds.js
Labels: Back-End

#66 Feature/record post
  Client/buddy/public/index.html
  Client/buddy/src/apollo/apollo.js
  Client/buddy/src/apollo/queries/CardItem/addCard.js
  Client/buddy/src/app.jsx
  Client/buddy/src/app.module.css
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/modal/oneButtonModal.jsx
  Client/buddy/src/components/modal/oneButtonModal.module.css
  Client/buddy/src/components/recordFeed/recordFeed.module.css
  Client/buddy/src/components/recordPost/recordPost.jsx
  Client/buddy/src/components/recordPost/recordPost.module.css
  Client/buddy/src/icons.js
Labels: Front-End

#70 [feat] 데이터 null || error 처리
  Client/buddy/src/components/button/button.jsx
  Client/buddy/src/components/feedPage/errorPage.jsx
  Client/buddy/src/components/feedPage/feedPage.module.css
  Client/buddy/src/components/feedPage/nullPage.jsx
  Client/buddy/src/components/recordFeed/recordFeed.jsx
  Client/buddy/src/components/selectOption/selectOption.jsx
  Client/buddy/src/icons.js
Labels: Front-End

#71 [feat] 유저 닉네임 리턴 API
  Server/lib/model/schema.prisma
  Server/lib/resolver-utils/UserInfo.js
  Server/lib/resolver/users.js
  Server/lib/typeDefs/Query.js
Labels: Back-End

#72 Feature/record post
  Client/buddy/public/index.html
  Client/buddy/src/apollo/queries/login/login.js
  Client/buddy/src/app.jsx
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/myProfile/myProfile.jsx
  Client/buddy/src/components/myProfile/myProfile.module.css
  Client/buddy/src/icons.js
  Client/buddy/src/services/PrivateRoute.jsx
  Client/buddy/src/services/PublicRoute.jsx
Labels: Front-End

#73 [feat]캘린더 ui 추가
  Client/buddy/package.json
  Client/buddy/src/app.jsx
  Client/buddy/src/components/calendar/calendar.jsx
  Client/buddy/src/components/calendar/calendar.module.css
  Client/buddy/src/components/calendar/calendarbar.jsx
  Client/buddy/src/components/calendar/calendarbar.module.css
  Client/buddy/src/components/login/KakaoLoginImg.svg
  Client/buddy/src/components/login/kakaoLogin.jsx
  Client/buddy/src/components/login/login.jsx
  Client/buddy/src/components/login/login.module.css
  Client/buddy/src/components/modal/calendarModal.jsx
  Client/buddy/src/components/modal/calendarModal.module.css
  Client/buddy/src/components/myProfile/myProfile.jsx
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/components/navBar/navbarcontents.jsx
  Client/buddy/src/components/recordPost/recordPost.jsx
  Client/buddy/src/icons.js
  Client/buddy/src/index.js
  Client/buddy/src/routes/login.jsx
  Client/buddy/src/routes/main.jsx
  Client/buddy/src/routes/navbar.jsx
  Client/buddy/src/routes/record.jsx
  Client/buddy/yarn.lock
Labels: Front-End

#74 코드 스타일 수정
  Client/buddy/src/components/calendar/calendar.jsx
  Client/buddy/src/components/modal/oneButtonModal.jsx
  Client/buddy/src/components/myProfile/myProfile.jsx
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/icons.js
Labels: Front-End

#75 css 수정 및 400에러 처리
  Client/buddy/src/components/button/button.jsx
  Client/buddy/src/components/cardList/cardList.module.css
  Client/buddy/src/components/feedPage/feedPage.module.css
  Client/buddy/src/components/myProfile/myProfile.jsx
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/recordFeed/recordFeed.jsx
  Client/buddy/src/components/recordFeed/recordFeed.module.css
  Client/buddy/src/components/recordPost/recordPost.jsx
  Client/buddy/src/components/recordPost/recordPost.module.css
  Client/buddy/src/components/selectOption/selectOption.jsx
  Client/buddy/src/components/selectOption/selectOption.module.css
Labels: Front-End

#76 [feat] 닉네임 'A003' 에서 '버디A003' 으로 변경
  Server/lib/resolver-utils/SocialLogin.js
Labels: Back-End

#77 [feat] 로그인 여부에 따른 nav bar 내용 변경
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/icons.js
Labels: Front-End

#79 [fix] console 에러 해결
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/index.js
Labels: Front-End

#80 [feat] 버튼 선택 시 변경되지 않게 수정
  Client/buddy/src/apollo/apollo.js
  Client/buddy/src/apollo/queries/login/login.js
  Client/buddy/src/apollo/queries/users/users.js
  Client/buddy/src/app.jsx
  Client/buddy/src/components/button/button.jsx
  Client/buddy/src/components/loader/loader.jsx
  Client/buddy/src/components/login/login.jsx
  Client/buddy/src/components/login/loginContents.jsx
  Client/buddy/src/components/login/naverLogin.jsx
  Client/buddy/src/components/myProfile/myProfile.jsx
  Client/buddy/src/components/myProfile/myProfile.module.css
  Client/buddy/src/components/recordPost/recordPost.jsx
  Client/buddy/src/components/recordPost/recordPost.module.css
  Client/buddy/src/components/selectOption/selectOption.jsx
  Client/buddy/src/components/selectOption/selectOption.module.css
  Client/buddy/src/routes/login.jsx
Labels: Front-End

#81 네이버 로그인 이미지 커스텀 , 뒤로 가기 버튼 컴포넌트 생성
  Client/buddy/src/components/goBack/goBackBtn.jsx
  Client/buddy/src/components/login/naverLogin.jsx
  Client/buddy/src/components/recordPost/recordPost.module.css
  Client/buddy/src/icons.js
Labels: Front-End

#82 Feature/calendar date
  Client/buddy/src/app.jsx
  Client/buddy/src/app.module.css
  Client/buddy/src/components/calendar/calendar.jsx
  Client/buddy/src/components/calendar/calendar.module.css
  Client/buddy/src/components/calendar/calendarbar.jsx
  Client/buddy/src/components/calendar/calendarbar.module.css
  Client/buddy/src/components/login/kakaoLogin.jsx
  Client/buddy/src/components/login/login.module.css
  Client/buddy/src/components/login/loginContents.jsx
  Client/buddy/src/components/login/로그인.png
  Client/buddy/src/components/modal/calendarModal.jsx
  Client/buddy/src/components/modal/calendarModal.module.css
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/components/recordPost/recordPost.jsx
Labels: Front-End

#83 메인 로고 클릭 시 새로고침
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardItem/cardItem.module.css
  Client/buddy/src/components/modal/cardModal.jsx
  Client/buddy/src/components/modal/cardModal.module.css
  Client/buddy/src/components/navBar/navBar.jsx
Labels: Front-End

#84 기록 후 바로 반영되도록 수정
  Client/buddy/src/components/modal/oneButtonModal.jsx
  Client/buddy/src/components/recordFeed/recordFeed.jsx
  Client/buddy/src/components/recordPost/recordPost.module.css
  Client/buddy/src/components/toggle/toggle.jsx
Labels: Front-End

#85 [hotfix]로그인 후 기록 화면 접근 시 반영 안되는 문제
  Client/buddy/src/apollo/apollo.js
  Client/buddy/src/apollo/queries/login/login.js
  Client/buddy/src/components/login/naverLogin.jsx
  Client/buddy/src/components/recordFeed/recordFeed.jsx
Labels: Front-End

#86 네비바에 닉넴 불러오기
  Client/buddy/src/components/navBar/navBar.jsx
Labels: Front-End

#87 Feature/calendar date
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/icons.js
Labels: Front-End

#88 [fix]icons 에러 수정
  Client/buddy/public/index.html
  Client/buddy/src/icons.js
Labels: Front-End

#91 [styles] favicon 및 Title 수정
  Client/buddy/public/favicon.ico
  Client/buddy/public/index.html
Labels: Front-End

#92 [style] css 조정
  Client/buddy/src/components/modal/twoButtonModal.module.css
  Client/buddy/src/components/navBar/navBar.module.css
  Client/buddy/src/components/recordFeed/recordFeed.module.css
Labels: Front-End

#93 [hotfix]모달 창 겹치는 문제
  Client/buddy/package.json
  Client/buddy/public/Favicon.ico
  Client/buddy/src/components/Intro/intro.jsx
  Client/buddy/src/components/login/KakaoLoginImg.svg
  Client/buddy/src/components/login/kakaoLogin.jsx
  Client/buddy/src/components/modal/twoButtonModal.module.css
  Client/buddy/yarn.lock
Labels: Front-End

#94 [style]기록하기버튼, 브라우저 css조정
  Client/buddy/src/app.jsx
  Client/buddy/src/app.module.css
  Client/buddy/src/components/recordFeed/recordFeed.module.css
Labels: Front-End

#95 Feature/cssfix
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/components/recordFeed/recordFeed.module.css
Labels: Front-End

#96 [feat] 기록하기 뒤로가기 버튼추가 및 캘린더 모달 css 수정
  Client/buddy/src/components/calendar/calendarbar.jsx
  Client/buddy/src/components/calendar/calendarbar.module.css
  Client/buddy/src/components/modal/calendarModal.module.css
  Client/buddy/src/components/recordPost/recordPost.jsx
Labels: Front-End

#97 [feat]로그인 하지 않았을 때 좋아요 버튼 클릭시 로그인 팝업 띄우기
  Client/buddy/package.json
  Client/buddy/src/components/Intro/intro.jsx
  Client/buddy/src/components/cardItem/cardItem.jsx
  Client/buddy/src/components/cardList/cardList.jsx
  Client/buddy/src/components/modal/infoModal.jsx
  Client/buddy/src/components/modal/infoModal.module.css
  Client/buddy/src/icons.js
  Client/buddy/yarn.lock
Labels: Front-End

#98 [feat] pace-buddy info modal 기능 추가
  Client/buddy/src/components/modal/infoModal.jsx
  Client/buddy/src/components/modal/infoModal.module.css
  Client/buddy/src/components/navBar/navBar.jsx
  Client/buddy/src/icons.js
Labels: Front-End

#99 [feat] 로그아웃 구현
  Client/buddy/src/components/loader/loader.jsx
  Client/buddy/src/components/modal/twoButtonModal.jsx
  Client/buddy/src/components/myProfile/myProfile.jsx
  Client/buddy/src/components/recordFeed/recordFeed.jsx
  Client/buddy/src/components/recordFeed/recordFeed.module.css
Labels: Front-End

#100 [refactor]로더 css 수정
  Client/buddy/src/components/loader/loader.jsx
Labels: Front-End

#101 [style] Info 모달 수정 등 css 수정
  Client/buddy/src/components/login/login.module.css
  Client/buddy/src/components/modal/infoModal.jsx
  Client/buddy/src/components/modal/infoModal.module.css
  Client/buddy/src/components/recordFeed/recordFeed.module.css
  Client/buddy/src/icons.js
Labels: Front-End

#102 [style] 로그인 및 모달창 css 수정
  Client/buddy/src/components/login/login.module.css
  Client/buddy/src/components/login/loginContents.jsx
  Client/buddy/src/components/modal/infoModal.module.css
  Client/buddy/src/icons.js
Labels: Front-End

#103 [style] Info 모달 Close 띄우기
  Client/buddy/src/components/modal/infoModal.module.css
Labels: Front-End
